[features]
seeds = false
[programs.localnet]
solana_file_sharing_system = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/athar/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
